"""initial schema

Revision ID: f58f45b477fe
Revises: 
Create Date: 2026-03-12 16:16:46.198919

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f58f45b477fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fips_code', sa.String(length=5), nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('arcgis_base_url', sa.String(length=512), nullable=True),
    sa.Column('hub_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fips_code')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fips_place_code', sa.String(length=10), nullable=True),
    sa.Column('zoning_source', sa.String(length=50), nullable=True),
    sa.Column('zoning_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_municipality', 'municipalities', ['county_id', 'name'], unique=True)
    op.create_table('discovered_layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('layer_name', sa.String(length=255), nullable=False),
    sa.Column('geometry_type', sa.String(length=50), nullable=True),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_record_count', sa.Integer(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('spatial_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_queryable', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_discovered_layer', 'discovered_layers', ['data_source_id', 'service_name', 'service_type', 'layer_id'], unique=True)
    op.create_table('zoning_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regulations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_zoning_district', 'zoning_districts', ['municipality_id', 'code'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('features_fetched', sa.Integer(), nullable=False),
    sa.Column('features_stored', sa.Integer(), nullable=False),
    sa.Column('features_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['layer_id'], ['discovered_layers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoning_geometries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoning_district_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('source_layer_id', sa.Integer(), nullable=True),
    sa.Column('zone_code', sa.String(length=50), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['source_layer_id'], ['discovered_layers.id'], ),
    sa.ForeignKeyConstraint(['zoning_district_id'], ['zoning_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gis_features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('source_layer_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('layer_name', sa.String(length=255), nullable=False),
    sa.Column('feature_id', sa.String(length=100), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_layer_id'], ['discovered_layers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gis_features_attrs', 'gis_features', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index('idx_gis_features_layer', 'gis_features', ['county_id', 'source_layer_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('source_layer_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('pin', sa.String(length=50), nullable=False),
    sa.Column('prop_address', sa.String(length=512), nullable=True),
    sa.Column('prop_city', sa.String(length=100), nullable=True),
    sa.Column('prop_state', sa.String(length=2), nullable=True),
    sa.Column('prop_zip', sa.String(length=10), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('property_class', sa.String(length=50), nullable=True),
    sa.Column('class_description', sa.String(length=255), nullable=True),
    sa.Column('assessed_value_land', sa.BigInteger(), nullable=True),
    sa.Column('assessed_value_bldg', sa.BigInteger(), nullable=True),
    sa.Column('assessed_value_total', sa.BigInteger(), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('tax_rate', sa.Double(), nullable=True),
    sa.Column('tax_amount', sa.Double(), nullable=True),
    sa.Column('acreage', sa.Double(), nullable=True),
    sa.Column('land_sqft', sa.Double(), nullable=True),
    sa.Column('bldg_sqft', sa.Integer(), nullable=True),
    sa.Column('bldg_age', sa.Integer(), nullable=True),
    sa.Column('lot_dimensions', sa.String(length=255), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('township', sa.String(length=255), nullable=True),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_layer_id'], ['discovered_layers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parcels_county_pin', 'parcels', ['county_id', 'pin'], unique=True)
    op.create_index('idx_parcels_municipality', 'parcels', ['municipality'], unique=False)
    op.create_index('idx_parcels_raw', 'parcels', ['raw_attributes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parcels_raw', table_name='parcels', postgresql_using='gin')
    op.drop_index('idx_parcels_municipality', table_name='parcels')
    op.drop_index('idx_parcels_county_pin', table_name='parcels')
    op.drop_table('parcels')
    op.drop_index('idx_gis_features_layer', table_name='gis_features')
    op.drop_index('idx_gis_features_attrs', table_name='gis_features', postgresql_using='gin')
    op.drop_table('gis_features')
    op.drop_table('zoning_geometries')
    op.drop_table('ingestion_runs')
    op.drop_index('uq_zoning_district', table_name='zoning_districts')
    op.drop_table('zoning_districts')
    op.drop_index('uq_discovered_layer', table_name='discovered_layers')
    op.drop_table('discovered_layers')
    op.drop_index('uq_municipality', table_name='municipalities')
    op.drop_table('municipalities')
    op.drop_table('data_sources')
    op.drop_table('counties')
    # ### end Alembic commands ###
